name = "LoopOSMainAgentgodCommunication"
uuid = "c88efa1e-98af-4ac2-839b-69b53e3bc0ad"
version = "1.0.0"
authors = ["1m1 <imi@1m1.io>"]

[deps]
TheoryOfGodCommunication = "15374a12-0dc0-4e42-8d31-63918d40956c"
TheoryOfGodgod = "2387dfef-0ca6-4bf7-8c6c-1d9d362a4086"
TheoryOfGod = "e52bc0f9-12eb-4b66-a578-8c5dba4c0869"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
TheoryOfGodCommunication = ">=1.0.0"
TheoryOfGodgod = ">=3.0.0"
TheoryOfGod = ">=3.0.0"
ZMQ = ">=1.5.1"
